#define OP_DATA         0

#define OP_DATA_nop     0
#define OP_DATA_ret     1
#define OP_DATA_b       2
#define OP_DATA_bl      3
#define OP_DATA_blt     4
#define OP_DATA_bgt     5
#define OP_DATA_bge     6
#define OP_DATA_ble     7
#define OP_DATA_beq     8
#define OP_DATA_bne     9
#define OP_DATA_bllt    10
#define OP_DATA_blgt    11
#define OP_DATA_blge    12
#define OP_DATA_blle    13
#define OP_DATA_bleq    14
#define OP_DATA_blne    15
#define OP_DATA_MAX     31

#define OP_RRI          1

#define OP_RRI_add      0
#define OP_RRI_sub      1
#define OP_RRI_mul      2
#define OP_RRI_div      3
#define OP_RRI_mod      4
#define OP_RRI_and      5
#define OP_RRI_or       6
#define OP_RRI_xor      7
#define OP_RRI_shl      8
#define OP_RRI_shr      9
#define OP_RRI_rol      10
#define OP_RRI_ror      11
#define OP_RRI_ldr      12
#define OP_RRI_str      13
#define OP_RRI_ldrb     14
#define OP_RRI_strb     15
#define OP_RRI_ldrw     16
#define OP_RRI_strw     17
#define OP_RRI_mov      18
#define OP_RRI_MAX      31

#define OP_RRR          2

#define OP_RRR_add      0
#define OP_RRR_sub      1
#define OP_RRR_mul      2
#define OP_RRR_div      3
#define OP_RRR_mod      4
#define OP_RRR_and      5
#define OP_RRR_or       6
#define OP_RRR_xor      7
#define OP_RRR_shl      8
#define OP_RRR_shr      9
#define OP_RRR_rol      10
#define OP_RRR_ror      11
#define OP_RRR_ldr      12
#define OP_RRR_str      13
#define OP_RRR_ldrb     14
#define OP_RRR_strb     15
#define OP_RRR_ldrw     16
#define OP_RRR_strw     17
#define OP_RRR_tst      18
#define OP_RRR_MAX      63

#define OP_RI           3

#define OP_RI_cbz       0
#define OP_RI_cbnz      1
#define OP_RI_lea       2
#define OP_RI_movk      3
#define OP_RI_movz      4
#define OP_RI_svc       5
#define OP_RI_br        6
#define OP_RI_blr       7
#define OP_RI_brlt      8
#define OP_RI_brgt      9
#define OP_RI_brge      10
#define OP_RI_brle      11
#define OP_RI_breq      12
#define OP_RI_brne      13
#define OP_RI_blrlt     14
#define OP_RI_blrgt     15
#define OP_RI_blrge     16
#define OP_RI_blrle     17
#define OP_RI_blreq     18
#define OP_RI_blrne     19
#define OP_RI_MAX       31
